apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-frontend-cache-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/tmp/kube"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-frontend-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: hovhanneshovakimyan/k8sproject:ex-2.02-v1.0-backend # Updated image name
          ports:
            - containerPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-frontend
  template:
    metadata:
      labels:
        app: todo-frontend
    spec:
      containers:
        - name: todo-frontend
          image: hovhanneshovakimyan/k8sproject:ex-2.02-v1.0-frontend # Updated image name
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: cache-volume
              mountPath: /cache
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: todo-frontend-cache-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: todo-backend
spec:
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: todo-backend
---
apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: todo-frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todo-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: todo-frontend
                port:
                  number: 3000
          - path: /todos
            pathType: Prefix
            backend:
              service:
                name: todo-backend
                port:
                  number: 3001
