apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cache-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Must match the PV's capacity
