apiVersion: v1
kind: Service
metadata:
  name: random-string-generator-service
  labels:
    app: random-string-generator
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: random-string-generator
