apiVersion: v1
kind: PersistentVolume
metadata:
  name: todo-frontend-cache-pv
  namespace: devops
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: "/tmp/kube"
