apiVersion: v1
kind: PersistentVolume
metadata:
  name: cache-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi # Adjust the size as needed
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/kube # Path on the node's filesystem
