apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-frontend-cache-pvc
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage
