apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: devops
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM= # base64 encoded "postgres"
  POSTGRES_PASSWORD: cG9zdGdyZXM= # base64 encoded "postgres"
  POSTGRES_DB: dG9kb3M= # base64 encoded "todos"
