apiVersion: v1
kind: Service
metadata:
  name: todo-backend
  namespace: devops
spec:
  ports:
    - port: 3001
      targetPort: 3001
  selector:
    app: todo-backend
---
apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  namespace: devops
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: todo-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: devops
spec:
  clusterIP: None
  ports:
    - port: 5432
      name: postgres
  selector:
    app: postgres
